language: node_js
node_js:
  - '8'
cache: npm
install:
  - npm ci
jobs:
  include:
    - stage: Build and test
      script:
        - npm run lint
        - npm run test
        - npm run build
    - stage: npm release
      script: npm run build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          branch: master
          tags: true